export const ADD_CITY = 'ADD_CITY'
export const REMOVE_CITY = 'REMOVE_CITY'
export const UPDATE_WEATHER_DATA = 'UPDATE_WEATHER_DATA'
export const UPDATE_HOURLY_WEATHER_DATA = 'UPDATE_HOURLY_WEATHER_DATA'

export const SET_REFRESHING = 'SET_REFRESHING'
export const SET_LOADING = 'SET_LOADING'
export const SET_ERROR = 'SET_ERROR'

export const OPEN_DAY_DETAIL = 'OPEN_DAY_DETAIL'
export const CLOSE_DAY_DETAIL = 'CLOSE_DAY_DETAIL'

export const ADD_NEW_CITY_PENDING = 'ADD_NEW_CITY_PENDING'
export const ADD_NEW_CITY_SUCCESS = 'ADD_NEW_CITY_SUCCESS'
export const ADD_NEW_CITY_FAILURE = 'ADD_NEW_CITY_FAILURE'
export const REFRESH_ALL_WEATHER_DATA_PENDING = 'REFRESH_ALL_WEATHER_DATA_PENDING'
export const REFRESH_ALL_WEATHER_DATA_SUCCESS = 'REFRESH_ALL_WEATHER_DATA_SUCCESS'
export const REFRESH_ALL_WEATHER_DATA_FAILURE = 'REFRESH_ALL_WEATHER_DATA_FAILURE'